name: Update Prescription

on:
  workflow_dispatch:
    inputs:
      rxId:
        description: 'Prescription ID'
        required: true
      data:
        description: 'Prescription JSON'
        required: true
        default: '{}'  # Default empty JSON if none provided

permissions:
  contents: write

jobs:
  update-prescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validate and update prescriptions.json
        run: |
          # Create file if it doesn't exist
          if [ ! -f "prescriptions.json" ]; then
            echo "{}" > prescriptions.json
          fi

          # Validate input JSON
          echo "Validating input JSON..."
          echo "${{ github.event.inputs.data }}" | jq empty
          
          # Update the JSON file
          echo "Updating prescriptions.json..."
          jq --arg key "${{ github.event.inputs.rxId }}" \
             --argjson value "$(echo '${{ github.event.inputs.data }}' | jq .)" \
             '.[$key] = $value' prescriptions.json > temp.json && mv temp.json prescriptions.json

          # Show updated content for verification
          echo "Updated content:"
          cat prescriptions.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add prescriptions.json
          
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Updated prescription: ${{ github.event.inputs.rxId }}"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
