name: Update Prescription

on:
  workflow_dispatch:
    inputs:
      rxId:
        description: 'Prescription ID (e.g., RX-12345)'
        required: true
        type: string
      data:
        description: 'Prescription Data (as JSON string)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-prescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Process prescription data
        shell: bash
        env:
          RX_JSON: ${{ toJSON(fromJSON(github.event.inputs.data)) }}
        run: |
          # Create prescriptions.json if missing
          if [ ! -f "prescriptions.json" ]; then
            echo "{}" > prescriptions.json
          fi

          # Write the input data to a temp file
          echo "$RX_JSON" > input.json

          # Validate JSON structure
          if ! jq empty input.json; then
            echo "❌ Invalid JSON data received"
            exit 1
          fi

          # Merge the new prescription data
          jq --arg id "${{ github.event.inputs.rxId }}" \
             --slurpfile newData input.json \
             '.[$id] = $newData[0]' prescriptions.json > updated.json

          # Verify and replace the file
          if jq empty updated.json; then
            mv updated.json prescriptions.json
            echo "✅ Successfully updated prescriptions.json"
            jq . prescriptions.json
          else
            echo "❌ Failed to create valid updated JSON"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add prescriptions.json
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update prescription ${{ github.event.inputs.rxId }} [skip ci]"
            git push
          fi
