name: Update Prescription

on:
  workflow_dispatch:
    inputs:
      rxId:
        description: 'Prescription ID'
        required: true
      data:
        description: 'Prescription JSON'
        required: true

jobs:
  update-prescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history to avoid issues

      - name: Setup jq
        uses: extractions/setup-jq@v1
        with:
          version: '1.6'

      - name: Update prescriptions.json
        run: |
          # Check if file exists, if not create empty JSON
          if [ ! -f "prescriptions.json" ]; then
            echo "{}" > prescriptions.json
          fi

          # Update the JSON file
          jq --arg key "${{ github.event.inputs.rxId }}" \
             --argjson value "${{ github.event.inputs.data }}" \
             '.[$key] = $value' prescriptions.json > temp.json && mv temp.json prescriptions.json

          # Validate the updated file
          jq empty prescriptions.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add prescriptions.json
          
          # Only commit if there are changes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Updated prescription: ${{ github.event.inputs.rxId }}"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
