name: Update Prescription

on:
  workflow_dispatch:
    inputs:
      rxId:
        description: 'Prescription ID'
        required: true
      data:
        description: 'Prescription JSON'
        required: true

permissions:
  contents: write

jobs:
  update-prescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update prescriptions.json
        run: |
          # Create file if it doesn't exist
          if [ ! -f "prescriptions.json" ]; then
            echo "{}" > prescriptions.json
          fi

          # Update the JSON file
          jq --arg key "${{ github.event.inputs.rxId }}" \
             --argjson value "${{ github.event.inputs.data }}" \
             '.[$key] = $value' prescriptions.json > temp.json && mv temp.json prescriptions.json

          # Validate JSON
          jq empty prescriptions.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add prescriptions.json
          
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Updated prescription: ${{ github.event.inputs.rxId }}"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
